remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

# Site settings
title: Khalil D. Atkins
description: Full-Stack Developer | MERN Specialist
author: Khalil D. Atkins
email: khalilatkins420@gmail.com

# Social media links
social:
  github: KhalilA93
  linkedin: https://www.linkedin.com/in/khalil-atkins-0aa64a286

# Portfolio settings
show_downloads: false
show_social_nav: true
